services:
  all_system:
    image: all_system:${IMAGE_TAG:-latest}
    container_name: all_system_${IMAGE_PORT:-27001}
    ports:
      - "${IMAGE_PORT:-27001}:8000"
    volumes:
      - "${HOST_DATA:-/data/all_system}/${IMAGE_PORT:-27001}/logs:/app/logs"
      - "${HOST_DATA:-/data/all_system}/${IMAGE_PORT:-27001}/oss:/app/oss"
      - "${HOST_DATA:-/data/all_system}/${IMAGE_PORT:-27001}/config.py:/app/main/config.py"
    networks:
      - 1panel-network
    restart: unless-stopped   # 后台运行并自动重启



networks:
  1panel-network:
    external: true