services:
  all_system:
    image: ${IMAGE_PROJECT:-all_system}:${IMAGE_TAG:-latest}
    container_name: ${IMAGE_PROJECT:-all_system}_${IMAGE_SITE:-dev}
    volumes:
      - "${HOST_DATA:-/data/all_system}/${IMAGE_SITE:-dev}/logs:/app/logs"
      - "${HOST_DATA:-/data/all_system}/${IMAGE_SITE:-dev}/oss:/app/oss"
      - "${HOST_DATA:-/data/all_system}/${IMAGE_SITE:-dev}/config.py:/app/main/config.py"
    expose:
      - "8000"
    networks:
      - app-network
    restart: unless-stopped   # Run in background and auto-restart

networks:
  app-network:
    name: app-network
    driver: bridge
    external: true
